name: LoginSequence
version: '1.8.4'
main: top.mcocet.loginSequence.LoginSequence
api-version: '1.20'
description: A plugin to manage player login sequence and perform connectivity tests.
author: MCOCET
folia-supported: false

commands:
  logseq:
    description: 主命令用于管理登录序列和服务器状态
    usage: /<command> [子命令]
    aliases: [ls]
    permission: logseq.admin
    children:
      ping:
        description: 手动测试服务器连通性
        usage: /logseq ping
        permission: logseq.ping
      info:
        description: 请求远程服务器状态数据
        usage: /logseq info
        permission: logseq.info
      stavie:
        description: 查看服务器实时状态
        usage: /logseq stavie
        permission: logseq.stavie
      help:
        description: 显示帮助信息
        usage: /logseq help
        permission: logseq.help
      cmdpingtest:
        description: 执行静默连通性测试（仅控制台）
        usage: /logseq cmdpingtest
        permission: logseq.cmdpingtest
      list:
        description: 查看JSON存储的玩家数据
        usage: /logseq list
        permission: logseq.list
      link:
        description: 直接连接至服务器
        usage: /logseq link
        permission: logseq.link
      register:
        description: 注册玩家
        usage: /logseq register
        permission: logseq.register
      login:
        description: 登录玩家
        usage: /logseq login
        permission: logseq.login
  register:
    description: 注册新账户
    usage: /register <密码> [验证密码]
  login:
    description: 登录到您的账户
    usage: /login <密码>

permissions:
  logseq.admin:
    description: 登录序列插件的管理权限
    default: op
    children:
      logseq.ping: true
      logseq.info: true
      logseq.stavie: true
      logseq.help: true
      logseq.cmdpingtest: true
      logseq.list: true
      logseq.register: true
      logseq.login: true
      logseq.link: true
  logseq.ping:
    description: 执行连通性测试的权限
    default: false
  logseq.info:
    description: 请求服务器状态数据的权限
    default: false
  logseq.stavie:
    description: 查看服务器实时状态的权限
    default: false
  logseq.cmdpingtest:
    description: 执行静默连通性测试的权限
    default: false
  logseq.list:
    description: 查看JSON玩家数据的权限
    default: false
