# 远程服务器端口号
Port: 1234

# 远程服务器IP地址
ip: 127.0.0.1

# 是否开启远程服务器在线检测
pionli: false

# 子服务器名称（远程服务器）
server: lobby

#是否开启安全登录，即玩家第一次登加入时踢出玩家
sl: false

# 是否启用密码登录
pwl: false

# 重要提示：开启该选项会记录玩家数据
# 例如玩家登录时间，登录IP
# 如果您服务器的玩家允许您这么做，或者您愿意承担相应的法律风险，请将此选项设置为true
#pi_EULA协议内容如下：

pi_eula: false
  
  
################################################################################
  ====pi_EULA协议规则====
如果您同意本规则的内容，并且想要记录玩家数据，请将配置文件“Config.yml”中的“ip_eula: false”设置为“true”。
  
  1，同意Mojang EUIA中的所有内容
  2，本插件仅用与非商业项目，或有限度的商业项目
  3，记录到的玩家数据仅用于保存玩家何时登录过，并且承诺不进行任何违规行为
  4，不会将记录到的数据分享给其他人，（除非进行必要的诊断或者维权，将不会共享任何UserData.json中的内容）
  5，如果玩家数据泄露，或者您将该文件的内容共享出去后出现了严重事件，您愿意承担相应后果。
  6，由该选项引起的所有事件与玩家无关，与作者和服务器无关

 记录的数据为：玩家名称，玩家UUID，玩家最后一次登录时间，玩家最后一次登录IP，玩家初次登录时间，玩家初次登录IP，玩家用于安全登录的加密后密码
################################################################################