############### 此项目为远程服务器的配置 ###############
# 远程服务器端口号
Port: 1234

# 远程服务器IP地址
ip: 127.0.0.1

# 是否开启远程服务器在线检测
pionli: false

# 子服务器名称（远程服务器）
server: lobby

############### 此项目为BC/Velocity插件的配置（理论上使用插件的兼容性会更好） ###############
# 通过向BC/Velocity插件发送跳转指令，启用后将不再依赖传统的跳转方式
bevel: false

# BC/Velocity插件的监听端口号
bevport: 1254

# BC/Velocity插件的IP地址
bevip: 127.0.0.1

############### 此项目为插件其他的配置信息 ###############
#是否开启安全登录，即玩家第一次登加入时踢出玩家
sl: false

# 是否启用密码登录
pwl: false

# 玩家数据记录
# 重要提示：开启该选项会记录玩家数据，例如玩家登录时间，登录IP
# 如果您服务器的玩家允许您这么做，或者您愿意承担相应的法律风险，请将此选项设置为true
pi_eula: false
